
RegisterBoard:
      type: "object"
      required:
        - roomId
        - key
      properties:
        roomId:
          type: "string"
        key:
          type: "string"

# Reponses when create an user, status 200, status 403
components:
  schemas:
    Status200:
      title: "Successful"
      type: "object"
      properties:
        error: 
          type: "boolean"
          example: "false"
    Status400:
      title: "Export Error"
      type: "object"
      properties:
        message:
          type: "string"
          example: "Missing board ID"
          
# responses:
Response200:
  description: "Board Reserved"
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status200"
Response400:
  description: "Register Error"
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status400"
