# Reponses when create an user, status 200, status 403
BodyCreateToken:
      title: "Body create user"
      type: "object"
      required:
        - apiKey
        - secret
      properties:
        apiKey:
          type: "string"
        secret:
          type: "string"

components:
  schemas:
    Status200:
      title: "Successful"
      type: "object"
      properties:
        error:
          type: "boolean"
          example: "false"
        msg: 
          type: "string"
          example: "Access granted"
        token:
          type: "string"
          example: "TOKEN_TOKEN"
    Status403:
      title: "Forbbiden"
      type: "object"
      properties:
        error:
          type: "boolean"
          example: "true"
        msg: 
          type: "string"
          example: "Access forbidden"
          
# responses:
Response200:
  description: "Token created"
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status200"
Response403:
  description: "Forbbiden."
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status403"
