
BodyConfigRoom:
      title: "Body create custom token"
      type: "object"
      required:
        - room_id
        - start_time
        - end_time
        - school
        - return_url
      properties:
        room_id:
          type: "string"
        start_time:
          type: "string"
        end_time:
          type: "string"
        school:
          type: "string"
        return_url:
          type: "string"

# Reponses when create an user, status 200, status 403
components:
  schemas:
    Status200:
      title: "Successful"
      type: "object"
      properties:
        error: 
          type: "boolean"
          example: "false"
        msg:
          type: "string"
          example: "Data saved successfully"
    Status400:
      title: "Forbbiden"
      type: "object"
      properties:
        error: 
          type: "boolean"
          example: "true"
        msg:
          type: "string"
          example: "PARAM is missing or invalid"
    Status500:
      title: "Error 500"
      type: "object"
      properties:
        error: 
          type: "boolean"
          example: "true"
        msg:
          type: "string"
          example: "There was an unknown error saving data into database"
          
# responses:
Response200:
  description: "Room configure"
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status200"
Response400:
  description: "Forbbiden"
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status400"
Response500:
  description: "Error 500"
  content:
    application/json:
      schema:
        $ref: "#/components/schemas/Status500"
